### ISSUE TITLE
ModuleNotFoundError: No module named 'sslyze.plugins.certificate_info_plugin'

### ISSUE THREAD

**Issue by thaisonnam** [0xInfection/TIDoS-Framework#102]
Hi team,
I got issue when build Tidos-framework.
**Env:**
+ Kali 2020.1
+ Python 3.8
**Log:**
~/tidos-framework$ sudo python3 tidos.py 
Traceback (most recent call last):
  File "tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/home/toor/tidos-framework/core/tidos_main.py", line 36, in <module>
    from core.Enumeration.scanenum import *
  File "/home/toor/tidos-framework/core/Enumeration/scanenum.py", line 24, in <module>
    from ssltlsscan import *
  File "modules/0x02-Scanning+Enumeration/ssltlsscan.py", line 18, in <module>
    from sslyze.plugins.certificate_info_plugin import CertificateInfoScanCommand
ModuleNotFoundError: No module named 'sslyze.plugins.certificate_info_plugin'

Please help resolved it.
--
Thanks,
ThaiHo

**Comment by omemishra** [comment]
i am getting same error

**Comment by znnt0** [comment]
The tool is under development by the designer and did not work for everyone

**Comment by VainlyStrain** [comment]
Hey!

This may have multiple reasons:

* this seems to be TIDoS < 2.0. Versions below 2.0 only work with Python2, so Python3.8 will cause errors.
* did you install the pip requirements?
  * no: run `pip install requirements.txt`
  * yes: did you use the `--user` flag? If so, you need to link .local to your global variables, since tidos is run as root user

Hope this helped!
Greetings
