### ISSUE TITLE
No module named functools_lru_cache

### ISSUE THREAD

**Issue by KiRyX112** [0xInfection/TIDoS-Framework#108]
It throws this error on startup. I tried to install this package pip install backports.functools_lru_cache but it didn't help

**Comment by VainlyStrain** [comment]
Hey!

Unfortunately, I do not know what is causing this error. Could you please post the whole stack trace? Maybe I'll be able to conclude what's going wrong.

Greetings

**Comment by alide123321** [comment]
im having the same problem 

![Capture](https://user-images.githubusercontent.com/47161857/96598456-8e62e500-12f7-11eb-87a2-facf9b406215.PNG)

**Comment by VainlyStrain** [comment]
This is indeed strange. Maybe, your pip command defaults to pip3. Does the error persist if you use `pip2` to install the library? If so, maybe one of the answers [https://stackoverflow.com/questions/47179433/python-2-7-functools-lru-cache-does-not-import-although-installed](here) is able to solve it?

If the issue still persists, maybe upgrading to TIDoS 2.0 will resolve the issue. Since it is based on Python3, it doesn't need the backports.

I hope you'll find a working and convenient solution. If so, let me know the fix :+1: 

Greetings
