### ISSUE TITLE
ImportError: No module named mysql.connector

### ISSUE THREAD

**Issue by sanebane** [0xInfection/TIDoS-Framework#112]
Tools$ sudo tidos

Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 17, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 22, in <module>
    from sqlbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/sqlbrute.py", line 15, in <module>
    import mysql.connector as mysql
ImportError: No module named mysql.connector

**Comment by sanebane** [comment]
I have manually installed mysql.connector but now there is a new error, "xmpp" error,  Tried to install it manualy but I was not able to find xmpp module in python. Please help

**Comment by VainlyStrain** [comment]
Hi!

What do you mean by "installing it manually"? Which package did you install (or built from source)?

xmpp is indeed quite troublesome. Some reported having gotten it working by installing the python2-xmpp package for TIDoS versions below 2.0. Maybe you'll have luck there?

Alternatively, you can switch to the Python3 TIDoS 2.0 version. Since I didn't find a fitting XMPP library for Python3 yet, the module causing the error is currently disabled (and thus no ImportError will be raised).

Sorry for not being able to give more precise advice right now.

Greetings
